// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto
#ifndef GRPC_hello_2eproto__INCLUDED
#define GRPC_hello_2eproto__INCLUDED

#include "hello.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace userteste {

class TesteService final {
 public:
  static constexpr char const* service_full_name() {
    return "userteste.TesteService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::userteste::AgeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userteste::AgeResponse>> AsyncGetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userteste::AgeResponse>>(AsyncGetAgeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userteste::AgeResponse>> PrepareAsyncGetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userteste::AgeResponse>>(PrepareAsyncGetAgeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest* request, ::userteste::AgeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest* request, ::userteste::AgeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userteste::AgeResponse>* AsyncGetAgeRaw(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userteste::AgeResponse>* PrepareAsyncGetAgeRaw(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::userteste::AgeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userteste::AgeResponse>> AsyncGetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userteste::AgeResponse>>(AsyncGetAgeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userteste::AgeResponse>> PrepareAsyncGetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userteste::AgeResponse>>(PrepareAsyncGetAgeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest* request, ::userteste::AgeResponse* response, std::function<void(::grpc::Status)>) override;
      void GetAge(::grpc::ClientContext* context, const ::userteste::AgeRequest* request, ::userteste::AgeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::userteste::AgeResponse>* AsyncGetAgeRaw(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::userteste::AgeResponse>* PrepareAsyncGetAgeRaw(::grpc::ClientContext* context, const ::userteste::AgeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetAge_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetAge(::grpc::ServerContext* context, const ::userteste::AgeRequest* request, ::userteste::AgeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAge() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetAge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAge(::grpc::ServerContext* /*context*/, const ::userteste::AgeRequest* /*request*/, ::userteste::AgeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAge(::grpc::ServerContext* context, ::userteste::AgeRequest* request, ::grpc::ServerAsyncResponseWriter< ::userteste::AgeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetAge<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetAge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAge() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::userteste::AgeRequest, ::userteste::AgeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::userteste::AgeRequest* request, ::userteste::AgeResponse* response) { return this->GetAge(context, request, response); }));}
    void SetMessageAllocatorFor_GetAge(
        ::grpc::MessageAllocator< ::userteste::AgeRequest, ::userteste::AgeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::userteste::AgeRequest, ::userteste::AgeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAge(::grpc::ServerContext* /*context*/, const ::userteste::AgeRequest* /*request*/, ::userteste::AgeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAge(
      ::grpc::CallbackServerContext* /*context*/, const ::userteste::AgeRequest* /*request*/, ::userteste::AgeResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetAge<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetAge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAge() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetAge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAge(::grpc::ServerContext* /*context*/, const ::userteste::AgeRequest* /*request*/, ::userteste::AgeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAge() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetAge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAge(::grpc::ServerContext* /*context*/, const ::userteste::AgeRequest* /*request*/, ::userteste::AgeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAge(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAge() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAge(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAge(::grpc::ServerContext* /*context*/, const ::userteste::AgeRequest* /*request*/, ::userteste::AgeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAge(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAge() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::userteste::AgeRequest, ::userteste::AgeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::userteste::AgeRequest, ::userteste::AgeResponse>* streamer) {
                       return this->StreamedGetAge(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAge(::grpc::ServerContext* /*context*/, const ::userteste::AgeRequest* /*request*/, ::userteste::AgeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAge(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::userteste::AgeRequest,::userteste::AgeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetAge<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetAge<Service > StreamedService;
};

}  // namespace userteste


#endif  // GRPC_hello_2eproto__INCLUDED
